#SPDX-License-Identifier: MIT-0
---
# # tasks file for task1
#   - name: Ensure SSH (Port 22) is open to the internet in the default security group
#     amazon.aws.ec2_security_group_rule:
#       group_name: "default" # Target the 'default' security group
#       # IMPORTANT: If you have multiple VPCs in us-east-2, you might need to specify the vpc_id
#       # to ensure you're modifying the correct 'default' security group.
#       # You can find your VPC ID in the AWS Console under VPC -> Your VPCs.
#       # vpc_id: "your_vpc_id_here"
#       region: us-east-2 # Must match the region where your instances are launched
#       aws_access_key: "{{ec2_access_key}}"
#       aws_secret_key: "{{ec2_secret_key}}"
#       ip_protocol: tcp
#       from_port: 22
#       to_port: 22
#       cidr_ip: 0.0.0.0/0 # Allows SSH from anywhere (less secure, consider "My IP" in production)
#       direction: ingress # Specifies it's an inbound rule
#       state: present # Ensures the rule exists


  # tasks file for task1
  - name: Ensure SSH (Port 22) is open to the internet in the default security group
    amazon.aws.ec2_group:
      name: default
      description: Default security group
      region: us-east-2
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      rules:
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      state: present


  - name: Launch 2 ubuntu instance with a public IP address
    amazon.aws.ec2_instance:
      name: "ansible-ubuntu"
      key_name: "awsKey"
      # vpc_subnet_id: subnet-013744e41e8088axx
      instance_type: "{{type}}"
      security_group: default
      region: us-east-2
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: ami-04f167a56786e4b09
      count: 2

  - name: Launch 1 amazon-linux instance with a public IP address
    amazon.aws.ec2_instance:
      name: "ansible-amazon-linux"
      key_name: "awsKey"
      # vpc_subnet_id: subnet-013744e41e8088axx
      instance_type: "{{type}}"
      security_group: default
      region: us-east-2
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: ami-06c8f2ec674c67112
